Fixed merge conflicts (#4)
* Update main.yml

* added @api tags

* fix api tests

* yaml refactor

* Fix yaml error

* Update main.yml

* renamed steps

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,12 +1,14 @@
-name: Daily Playwright Test
+name: Playwright CI
 
 on:
   push:
-    branches: [ '**' ]   # Triggert op elke push naar elke branch
-  workflow_dispatch:     # Handmatig starten blijft mogelijk
+    branches: [ '**' ]
+  workflow_dispatch:
+  schedule:
+    - cron: '0 13 * * *'
 
 jobs:
-  Smoke_test:
+  smoke_test:
     if: github.ref != 'refs/heads/main' && github.event_name == 'push'
     runs-on: ubuntu-latest
 
@@ -39,7 +41,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: allure-report
+          name: allure-report-smoke
           path: allure-report/
 
       - name: List allure-report directory
@@ -53,8 +55,8 @@ jobs:
           publish_dir: allure-report
           publish_branch: gh-pages
 
-  Regression_test:
-    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+  regression_test:
+    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'schedule'
     runs-on: ubuntu-latest
 
     steps:
@@ -86,7 +88,54 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: allure-report
+          name: allure-report-regression
+          path: allure-report/
+
+      - name: List allure-report directory
+        run: ls -l allure-report || echo "allure-report not found"
+
+      - name: Deploy Allure report to GitHub Pages
+        if: github.ref == 'refs/heads/main'
+        uses: peaceiris/actions-gh-pages@v3
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: allure-report
+          publish_branch: gh-pages
+
+  api_test:
+    if: github.event_name == 'push' || github.event_name == 'schedule'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 18
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Install Playwright browsers
+        run: npx playwright install --with-deps
+
+      - name: Run Playwright API tests
+        run: npx playwright test --grep @apiTest --reporter=allure-playwright
+
+      - name: Generate Allure report
+        uses: simple-elf/allure-report-action@v1.7
+        with:
+          allure_results: allure-results
+          allure_report: allure-report
+          keep_reports: 1
+
+      - name: Upload allure report artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: allure-report-api
           path: allure-report/
 
       - name: List allure-report directory
